version: '3'
services:
  nginx:
    restart: always
    image: 'nginx:latest'
    container_name: react-notepad-client
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    container_name: react-notepad-server
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - '5000:5000'
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=process.env.REACT_APP_GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET
      - CALLBACK_URL_GOOGLE=process.env.CALLBACK_URL_GOOGLE
    restart: always
